// Generated by https://quicktype.io

export interface player {
    name:      string;
    race:      string;
    class:     string;
    level:     number;
    nuts:      number;
    dm:        boolean;
    dm_points: number;
}
